apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::732365169092:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1D8JTFCTCC2B3
      username: system:node:{{EC2PrivateDNSName}}
      rolearn: arn:aws:iam::732365169092:role/UdacityFlaskDeployCBRole
      username: build
    - groups:
      - system:masters
      rolearn: arn:aws:iam::732365169092:role/UdacityFlaskDeployCBRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-03-23T00:32:21Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "109696"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c222e7d9-6c9d-11ea-8334-16410ad258d9
